import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Session from "@/session/Session";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session>
          <Navbar />
          {children}
        </Session>
      </body>
    </html>
  );
}
